name: Create a release pull request

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: echo-npm-version
        id: echo-version
        run: |
          echo v${{ steps.package-version.outputs.current-version}}

      - name: git-pr-release
        uses: bakunyo/git-pr-release-action@master
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: master
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TITLE: hoge
        run: |
          gem install -N git-pr-release -v "1.2.0"
          git-pr-release --no-fetch
